In [ ]:
from oo_cqed_rhf import CQEDRHFCalculator
import numpy as np
import psi4

In [ ]:
lambda_vector = [0.0, 0.0, 0.0]
# molecule string for H2O
molecule_string = """
0 1
    O      0.000000000000   0.000000000000  -0.068516219320
    H      0.000000000000  -0.790689573744   0.543701060715
    H      0.000000000000   0.790689573744   0.543701060715
no_reorient
no_com
symmetry c1
"""

# options for H2O
psi4_options = {
    "basis": "cc-pVDZ",
    "save_jk": True,
    "scf_type": "pk",
    "e_convergence": 1e-12,
    "d_convergence": 1e-12,
}


In [ ]:
calc = CQEDRHFCalculator(lambda_vector, molecule_string, psi4_options)
calc.calc_cqed_rhf_energy()

In [ ]:
expected_h2o_e = -76.016355284146
assert np.isclose(expected_h2o_e, calc.cqed_rhf_energy, 1e-9, 1e-9)

In [ ]:
calc.compute_nuclear_repulsion_gradient()
calc.compute_one_electron_integral_gradient_terms()
calc.compute_two_electron_integral_gradient_terms()
calc.compute_fock_matrix_term()

In [ ]:
calc.calc_scf_gradient(qed_wfn=True)

In [ ]:
print(calc.scf_grad)
print("Shape of nuclear repulsion gradient")
print(np.shape(calc.nuclear_repulsion_gradient))
print("Shape of Overlap Gradient")
print(np.shape(calc.overlap_gradient))
print("Shape of T gradient")
print(np.shape(calc.kinetic_gradient))
print("Shape of V gradient")
print(np.shape(calc.potential_gradient))
print("Shape of J gradient")
print(np.shape(calc.J_gradient))
print("Shape of K gradient")
print(np.shape(calc.K_gradient))
el_grads = calc.overlap_gradient + calc.kinetic_gradient + calc.potential_gradient + calc.J_gradient + calc.K_gradient 
my_grad = calc.nuclear_repulsion_gradient + el_grads.reshape(3,3)
print("My gradient")
print(my_grad)


In [ ]:
#print(calc.scf_grad -gradient)

In [ ]:
calc.calc_quadrupole_gradient()
# last output

#[[ 1.32601432e-18  9.99294165e-19 -2.77573793e-03]
# [ 1.03219418e-19  2.17498212e-04  1.62681438e-03]
# [-1.42923374e-18 -2.17498212e-04  1.62681438e-03]]

In [ ]:
calc.calc_numerical_gradient()

In [ ]:
calc.numerical_scf_gradient.reshape(3,3)-calc.scf_grad

In [ ]:
print("O_DSE Analytic GRAD")
print(calc.numerical_o_dse_gradient.reshape(3,3))


print("O_DSE Numeric GRAD")
print(calc.o_dse_gradient.reshape(3,3))

In [ ]:
calc.calc_dipole_dipole_gradient()

In [ ]:
print("K_DSE GRAD")
print(calc.numerical_K_dse_gradient.reshape(3,3))

print("ANALYTIC K_DSE GRAD")
print(calc.K_dse_gradient.reshape(3,3))




In [ ]:

print("E GRAD")
print(calc.numerical_energy_gradient.reshape(3,3))

sum_grad = calc.scf_grad + calc.numerical_o_dse_gradient.reshape(3,3) + calc.numerical_K_dse_gradient.reshape(3,3)

print("SUM GRAD")
print(sum_grad)

In [ ]:
total_gradient = calc.scf_grad + calc.K_dse_gradient.reshape(3,3) + calc.o_dse_gradient.reshape(3,3)
print(total_gradient)

# The numerical gradient for water in a cc-pVDZ basis set with this geometry and lambda = 0, 0, 0.05 is:

[[ 2.25601351e-10 -2.63201576e-10 -6.18353559e-02]

 [ 7.52004504e-11 -4.35898538e-02  3.09176777e-02]
 
 [ 0.00000000e+00  4.35898541e-02  3.09176786e-02]]

In [ ]:
_expected_gradient = np.array(
[[ 2.25601351e-10, -2.63201576e-10, -6.18353559e-02],
 [ 7.52004504e-11, -4.35898538e-02,  3.09176777e-02],
 [ 0.00000000e+00,  4.35898541e-02,  3.09176786e-02]])

print(_expected_gradient-calc.numerical_energy_gradient.reshape(3,3))