## This tests the QED-RHF gradient components against Hilbert's and against numerical components


In [1]:
from oo_cqed_rhf import CQEDRHFCalculator
import numpy as np
import psi4
psi4.core.be_quiet()

In [6]:
# Expected gradient contributions for Water in a STO-3G basis set with the following geometry:
h2o_string_b = """
         O            0.000000000000     0.000000000000    -0.068901000000
         H            0.000000000000    -0.790689573744     0.543701060715
         H            0.000000000000     0.790689573744     0.543701060715
no_reorient
nocom
symmetry c1
"""

# Expected gradient contributions for Water in a STO-3G basis set with the following geometry:
h2o_string_f = """
         O            0.000000000000     0.000000000000    -0.0689020000000
         H            0.000000000000    -0.790689573744     0.543701060715
         H            0.000000000000     0.790689573744     0.543701060715
no_reorient
nocom
symmetry c1
"""


# no cavity
lambda_vector = np.array([0, 0, 0.05])
print(lambda_vector)
# options for H2O
psi4_options = {
    "basis": "cc-pVDZ",
    "save_jk": True,
    "scf_type": "pk",
    "e_convergence": 1e-12,
    "d_convergence": 1e-12,
}





[0.   0.   0.05]


In [7]:
calc = CQEDRHFCalculator(lambda_vector, h2o_string_b, psi4_options)

# calculate the CQED-RHF energy and gradient at h2o_string_b
qed_rhf_energy, qed_rhf_grad = calc.calc_force_and_energy(h2o_string_b, use_psi4_scf_grad=False)
print("CQED-RHF Energy at h2o_string_b:", qed_rhf_energy)
print("CQED-RHF Gradient at h2o_string_b:\n", qed_rhf_grad)

# calculate the CQED-RHF energy and gradient at h2o_string_f
qed_rhf_energy_f, qed_rhf_grad_f = calc.calc_force_and_energy(h2o_string_f, use_psi4_scf_grad=False)
print("CQED-RHF Energy at h2o_string_f:", qed_rhf_energy_f)
print("CQED-RHF Gradient at h2o_string_f:\n", qed_rhf_grad_f)

CQED-RHF Energy at h2o_string_b: -76.01631020870477
CQED-RHF Gradient at h2o_string_b:
 [[-1.38789987e-16 -3.87985435e-16 -6.04398722e-02]
 [-3.13353414e-17 -4.34930517e-02  3.02199361e-02]
 [ 1.70125329e-16  4.34930517e-02  3.02199361e-02]]
CQED-RHF Energy at h2o_string_f: -76.01631009126474
CQED-RHF Gradient at h2o_string_f:
 [[ 3.07885818e-16  2.56179646e-16 -6.04406770e-02]
 [-9.74629668e-20 -4.34933131e-02  3.02203385e-02]
 [-3.07788355e-16  4.34933131e-02  3.02203385e-02]]
