## This tests the QED-RHF gradient components against Hilbert's and against numerical components


In [1]:
from oo_cqed_rhf import CQEDRHFCalculator
import numpy as np
import psi4

### Expected O_DSE gradient term from Hilbert

In [2]:
_expected_o_dse = np.array(
[[ 4.50564203e-20,  1.34441069e-18, -2.74087275e-03],
 [-5.50477740e-20,  1.05859828e-04,  1.82095121e-03],
 [ 9.99135370e-21, -1.05859828e-04,  1.82095121e-03]]
)

### Expected K_DSE gradient term from Hilbert

In [3]:
_expected_k_dse = np.array(
[[ 1.14641991e-19, -1.20129601e-18,  8.09949008e-04],
 [-5.05409763e-20, -3.61148015e-04, -8.55489341e-04],
 [-6.41010149e-20,  3.61148015e-04, -8.55489341e-04]]
)

In [4]:
# Expected gradient contributions for Water in a STO-3G basis set with the following geometry:
h2o_string = """
         O            0.000000000000     0.000000000000    -0.068516219320
         H            0.000000000000    -0.790689573744     0.543701060715
         H            0.000000000000     0.790689573744     0.543701060715
no_reorient
nocom
symmetry c1
"""

w = 0.07349864501573
# lambda: 0.05
# coupling g = 0.05 / sqrt(2*w)
g = 0.05 / np.sqrt(2.0 * w)

# no cavity
lambda_vector = np.array([0, 0, 0.05])
print(lambda_vector)
# options for H2O
psi4_options = {
    "basis": "sto-3g",
    "save_jk": True,
    "scf_type": "pk",
    "e_convergence": 1e-12,
    "d_convergence": 1e-12,
}





[0.   0.   0.05]


In [5]:
calc = CQEDRHFCalculator(lambda_vector, h2o_string, psi4_options)
calc.calc_cqed_rhf_energy()


Scratch directory: /tmp/
   => Libint2 <=

    Primary   basis highest AM E, G, H:  6, 6, 3
    Auxiliary basis highest AM E, G, H:  7, 7, 4
    Onebody   basis highest AM E, G, H:  -, -, -
    Solid Harmonics ordering:            Gaussian

*** tstart() called on CHEM9QDFT72ALT
*** at Tue Jun 17 20:46:46 2025

   => Loading Basis Set <=

    Name: STO-3G
    Role: ORBITAL
    Keyword: BASIS
    atoms 1   entry O          line    81 file /Users/jfoley19/miniconda3/envs/psi4_new/share/psi4/basis/sto-3g.gbs 
    atoms 2-3 entry H          line    19 file /Users/jfoley19/miniconda3/envs/psi4_new/share/psi4/basis/sto-3g.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              RHF Reference
                        1 Threads,    500 MiB Core
         -------------------------------------------------

In [6]:
calc.summary()

RHF Energy:           -74.96466254 Ha
CQED-RHF Energy:      -74.96009499 Ha
Dipole Energy:        0.00016237 Ha
Nuclear Repulsion:    8.80146556 Ha
Dipole Moment:        [4.88077911e-17 3.24153496e-15 6.58665211e-01]


In [7]:
calc.compute_canonical_gradients()

In [8]:
# print the total gradient
print(calc.canonical_gradient)

[[-3.04967191e-16  4.65412344e-16  1.05402411e-03]
 [ 1.73832759e-16 -1.93839853e-02 -5.27012056e-04]
 [ 1.31134432e-16  1.93839853e-02 -5.27012056e-04]]


In [9]:
# use psi4 to compute the gradient
calc.calc_scf_gradient(qed_wfn=True)


*** tstart() called on CHEM9QDFT72ALT
*** at Tue Jun 17 20:46:51 2025


         ------------------------------------------------------------
                                   SCF GRAD                          
                          Rob Parrish, Justin Turney,                
                       Andy Simmonett, and Alex Sokolov              
         ------------------------------------------------------------

  ==> Geometry <==

    Molecular point group: c1
    Full point group: C2v

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------
         O            0.000000000000     0.000000000000    -0.068516219320    15.994914619570
         H            0.000000000000    -0.790689573744     0.543701060715     1.007825032230
         H            0.000000000000     0.790689573744     0.54

array([[-3.04967191e-16,  6.63518455e-16,  1.05402411e-03],
       [ 1.73832759e-16, -1.93839853e-02, -5.27012057e-04],
       [ 1.31134432e-16,  1.93839853e-02, -5.27012057e-04]])

 seconds =       0.00 minutes
	total time  =          0 seconds =       0.00 minutes
Total time:
	user time   =       0.36 seconds =       0.01 minutes
	system time =       0.10 seconds =       0.00 minutes
	total time  =          5 seconds =       0.08 minutes


In [10]:
#print(calc.scf_grad)
# compute the numerical gradient
calc.calc_numerical_gradient()


Scratch directory: /tmp/
   => Libint2 <=

    Primary   basis highest AM E, G, H:  6, 6, 3
    Auxiliary basis highest AM E, G, H:  7, 7, 4
    Onebody   basis highest AM E, G, H:  -, -, -
    Solid Harmonics ordering:            Gaussian

*** tstart() called on CHEM9QDFT72ALT
*** at Tue Jun 17 20:46:51 2025

   => Loading Basis Set <=

    Name: STO-3G
    Role: ORBITAL
    Keyword: BASIS
    atoms 1   entry O          line    81 file /Users/jfoley19/miniconda3/envs/psi4_new/share/psi4/basis/sto-3g.gbs 
    atoms 2-3 entry H          line    19 file /Users/jfoley19/miniconda3/envs/psi4_new/share/psi4/basis/sto-3g.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              RHF Reference
                        1 Threads,    500 MiB Core
         -------------------------------------------------

In [11]:
print(F" My Analytical Gradient Matches Psi4's Gradient: {np.allclose(calc.scf_grad, calc.canonical_gradient, 1e-6, 1e-6)}")
error_norm = np.linalg.norm(calc.scf_grad-  calc.canonical_gradient)
print(F" Norm of difference is {error_norm}")

print(F" Numerical Gradient Matches Psi4's Gradient: {np.allclose(calc.numerical_energy_gradient.reshape(3,3), calc.canonical_gradient, 1e-6, 1e-6)}")
error_norm = np.linalg.norm(calc.numerical_energy_gradient.reshape(3,3)-  calc.canonical_gradient)
print(F" Norm of difference is {error_norm}")


print(F" Numerical Gradient Matches Psi4's Gradient: {np.allclose(calc.numerical_scf_gradient.reshape(3,3), calc.canonical_gradient, 1e-6, 1e-6)}")
error_norm = np.linalg.norm(calc.numerical_scf_gradient.reshape(3,3)-  calc.canonical_gradient)
print(F" Norm of difference is {error_norm}")


 My Analytical Gradient Matches Psi4's Gradient: True
 Norm of difference is 9.912797637962686e-13
 Numerical Gradient Matches Psi4's Gradient: False
 Norm of difference is 0.002392285847019441
 Numerical Gradient Matches Psi4's Gradient: False
 Norm of difference is 0.0008459788936484209


In [12]:
calc.calc_quadrupole_gradient() 


[[-8.50179782e-20 -6.75097808e-09 -2.74088600e-03]
 [ 1.23594531e-19  1.05862536e-04  1.82095059e-03]
 [-3.85765526e-20 -1.05855785e-04  1.82091640e-03]]


In [13]:
print("my o_dse gradient")
print(calc.o_dse_gradient.reshape(3,3))

my o_dse gradient
[[-8.50179782e-20 -6.75097808e-09 -2.74088600e-03]
 [ 1.23594531e-19  1.05862536e-04  1.82095059e-03]
 [-3.85765526e-20 -1.05855785e-04  1.82091640e-03]]


In [14]:
print("Expected o_dse gradient")
print(_expected_o_dse)

Expected o_dse gradient
[[ 4.50564203e-20  1.34441069e-18 -2.74087275e-03]
 [-5.50477740e-20  1.05859828e-04  1.82095121e-03]
 [ 9.99135370e-21 -1.05859828e-04  1.82095121e-03]]


In [15]:
calc.hilber_quadrupole_gradient()
print("Hilbert o_DSE")
print(calc.hilbert_o_dse.reshape(3,3))

Hilbert o_DSE
[[-8.50179782e-20 -6.75097808e-09 -2.74088600e-03]
 [ 1.23594531e-19  1.05862536e-04  1.82095059e-03]
 [-3.85765526e-20 -1.05855785e-04  1.82091640e-03]]


In [17]:
print(calc.o_dse_gradient.reshape(3,3) - calc.hilbert_o_dse.reshape(3,3))

[[ 0.00000000e+00 -8.27180613e-25  0.00000000e+00]
 [ 0.00000000e+00  1.35525272e-20  2.16840434e-19]
 [ 0.00000000e+00 -2.71050543e-20  2.16840434e-19]]


In [ ]:
print(calc.numerical_o_dse_gradient.reshape(3,3))

In [18]:
calc.calc_dipole_dipole_gradient_2()

In [19]:
print(calc.K_dse_gradient.reshape(3,3))

[[-2.60426483e-20  1.25026716e-08  8.09991000e-04]
 [-7.64938539e-21 -3.61150767e-04 -8.55489753e-04]
 [ 3.36920337e-20  3.61138264e-04 -8.55482237e-04]]


In [20]:
print(_expected_k_dse)

[[ 1.14641991e-19 -1.20129601e-18  8.09949008e-04]
 [-5.05409763e-20 -3.61148015e-04 -8.55489341e-04]
 [-6.41010149e-20  3.61148015e-04 -8.55489341e-04]]


In [21]:
_total_grad = calc.canonical_gradient + (calc.K_dse_gradient + calc.o_dse_gradient).reshape(3,3)
print("My Analytic QED-RHF Gradient")
print(_total_grad)

My Analytic QED-RHF Gradient
[[-3.05078252e-16  5.75169396e-09 -8.76870887e-04]
 [ 1.73948704e-16 -1.96392735e-02  4.38448777e-04]
 [ 1.31129547e-16  1.96392677e-02  4.38422110e-04]]


In [22]:
print("My numerical QED-RHF Gradient")
print(calc.numerical_energy_gradient.reshape(3,3))

My numerical QED-RHF Gradient
[[ 1.12800907e-09 -3.76003023e-10 -8.76898834e-04]
 [ 0.00000000e+00 -1.96392681e-02  4.38446221e-04]
 [ 0.00000000e+00  1.96392737e-02  4.38449981e-04]]


In [23]:
print("The Difference")
print(_total_grad-calc.numerical_energy_gradient.reshape(3,3))

print("Norm of Difference")
error_norm = np.linalg.norm(_total_grad-calc.numerical_energy_gradient.reshape(3,3))
print(error_norm)

The Difference
[[-1.12800937e-09  6.12769699e-09  2.79470663e-08]
 [ 1.73948704e-16 -5.40973234e-09  2.55600374e-09]
 [ 1.31129547e-16 -5.98200451e-09 -2.78710291e-08]]
Norm of Difference
4.084405208352919e-08
